#!/bin/bash
set -euo pipefail

live="/etc/nginx/aws_subnets"
staging="${live}.staging"
backup="${live}.bak"
PATH="$PATH:/usr/sbin:/usr/bin"
[[ $(whoami) == root ]] || { echo "requires root account"; exit 1 ;}
which awk curl nginx >/dev/null || { echo "requires: awk, curl, nginx"; exit 1 ;}

download(){
	url='https://ip-ranges.amazonaws.com/ip-ranges.json'
	curl -s $url | awk -F\" '$2 == "ip_prefix" {print "allow "$4";"}' | sort > $staging
}

non_zero() {
	test -s $staging
}

newer() {
	test $staging -nt $live
}

different() {
	! cmp --silent $staging $live
}

valid() {
	nginx -qt
}

reload_nginx() {
        nginx -s reload
}

if [[ ! -f $live ]]; then
	set -e
	download
	non_zero
	cp $staging $live
else
	set -e
	download
	non_zero
	newer
	different
	cp $live $backup
	cp $staging $live
fi

if valid; then
	reload_nginx
else
	cp $backup $live
fi

